apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
 StotageClassName: roboshop-ebs
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
    storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        name: ebs-dynamic-storage
        mountPath: /usr/share/nginx/html
  volumes:
    name: ebs-dynamic-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic

