apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: restore-pv-efs-static
spec:
  capacity:
    storage: 5Gi 
  accessModes:
   - ReadWriteOnce
  PersistantVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    fsType: ext4
    VolumeHandle: 44830fa8-79b4-406b-8b58-621ba25353fd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc-efs-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: restore-pvc-efs-static
      mountPath: /etc/nginx