apiVersion: apps/v1
kind: Deployment
metadata:  
  name: roboshop
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
spec:
 replicas: 1
 selector:
   matchLabels:
     component: mongodb
     project: roboshop
     env: dev
 template:
   metadata:
     labels:
       component: mongodb
       project: roboshop
       env: dev
   spec:
     containers:
      - name: mongodb
        image: srinunaik208/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service 
  namespace: roboshop
  labels: 
    project: roboshop
    dev: env
spec:
  selector:
    component: mongodb
    project: roboshop
    dev: env
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017

