# apiVersion: v1 
# kind: Secret 
# metadata:
#    name: mysql
#    namespace: roboshop
#    labels:
#      project: roboshop
#      component: mysql 
#      tier: database
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
# ---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mysql
    tier: database
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  selector:
    project: roboshop
    component: mysql
    tier: database
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: mysql
  namespace: roboshop 
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
 serviceName: mysql-headless
 replicas: 1
 selector:
   matchLabels:
      project: roboshop
      component: mysql
      tier: database
 template:
   metadata:
     labels:
       project: roboshop
       component: mysql
       tier: database
   spec:
     serviceAccountName: aws-secreat-manager
     volumes:
     - name: mysql-secret
       emptyDir: {}
     initContainers:
     - name: aws-cli 
       image:  amazon/aws-cli
       command: 
          - sh
          - -c
          - |
            aws secretsmanager get-secret-value --secret-id roboshop/mysql/password --query SecretString --output text | jq -r '.MYSQL_ROOT_PASSWORD' > /secret/secret.txt
       volumeMounts:
       - name: mysql-secret
         mountPath: secret
     containers:
     - name: mysql
       image: srinunaik208/mysql:v5
      #  envFrom:
      # #  - secretRef:
      # #      name: mysql
       volumeMounts:
       - name: mysql-storage
         mountPath: /var/lib/mysql
       - name: mysql-secret
         mountPath: secret
       

 volumeClaimTemplates:
 - metadata:
     name: mysql-storage
   spec:
     accessModes:
     - ReadWriteOnce
     storageClassName: roboshop
     resources:
        requests:
          storage: 4Gi


     