apiVersion: v1
kind: PersistentVolumeClaim
matadata:
  name: ebs-dynamic
spec:
  storageClassName: sc-ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ebs-dynamic
spec:
 containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-naginx-storage
      mountPath: /usr/share/nginx/html

volumes:
- name: ebs-naginx-storage
  persistentVolumeClaim:
   claimName: ebs-dynamic