apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: filesystem
  PersistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
   - ReadWriteMany
  volumeName: efs-static
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: efs-nginx
  labels:
    purpose: efs-demo
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: nginx-storage
         mountPath: /usr/shre/nginx/
  volumes:
   - name: nginx-storage
     persistentVolumeClaim:
      claimName: efs-static
---
apiVersion: v1
kind: Service
metadata: 
  name: efs-service
spec: 
  selector:
    purpose: efs-demo
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80


